version: "3"

services:

  # frontend:
  #   build: 
  #     dockerfile: Dockerfile.dev
  #     context: ../UC-FundamentosDevOps-FrontEnd/
  #   ports:
  #     - 8090:3000
  #   links:
  #     - backend
  #   depends_on:
  #     - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:5000
    env_file: .env
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    links:
      - mongo_db
    depends_on:
      - mongo_db
    volumes:
      - .:/app
    restart: on-failure

  mongo_db:
    image: mongo:latest
    ports:
      - 12345:27017
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    restart: always
    volumes:
      - ./mongo_db:/data/db