version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8005
    env_file: .env
    environment:
      - "MONGO_USER:${MONGO_USER}"
      - "MONGO_PASSWORD:${MONGO_PASSWORD}"
    links:
      - db
    depends_on:
      - db
    restart: on-failure

  db:
    image: mongo:latest
    ports:
      - 12345:27017
    environment:
      - "MONGO_INITDB_ROOT_USERNAME:${MONGO_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD:${MONGO_PASSWORD}"
    restart: on-failure
    volumes:
      - ~/mongodb/mongodb_democloud_api:/data/db