apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: myapp
  labels:
    app: ucreativa-proyecto-microservicios
    tier: backend
spec:
  selector:
    name: backend-deployment
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
