apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: myapp
  labels:
    app: ucreativa-proyecto-microservicios
    tier: backend
spec:
  selector:
    matchLabels:
      app: ucreativa-proyecto-microservicios
      name: backend-deployment
      tier: backend
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: ucreativa-proyecto-microservicios
        name: backend-deployment
        tier: backend
    spec:
      containers:
        - name: backend
          image: nabetse28/backend
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: mongo_user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: mongo_password
            - name: MONGO_SERVER
              value: mongo-svc
          ports:
            - containerPort: 5000
