apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: myapp
  labels:
    app: ucreativa-proyecto-microservicios
    tier: database
spec:
  selector:
    name: mongo-deployment
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
