apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: myapp
  labels:
    app: ucreativa-proyecto-microservicios
    tier: volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /mongo/data
