apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: myapp
  labels:
    app: ucreativa-proyecto-microservicios
    tier: database
spec:
  selector:
    matchLabels:
      app: ucreativa-proyecto-microservicios
      name: mongo-deployment
      tier: database
  template:
    metadata:
      labels:
        app: ucreativa-proyecto-microservicios
        name: mongo-deployment
        tier: database
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: mongo_user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: mongo_password
          volumeMounts:
            - name: data
              mountPath: /mongo/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongo-pvc
